---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: debian-9
  - name: centos-7
  - name: centos-6

suites:
  - name: default
    run_list:
      - recipe[minitest-handler]
      - recipe[terraform::default]
  - name: gpgme
    run_list:
      - recipe[minitest-handler]
      - recipe[terraform::gpgme]
